Repository micronaut-projects/micronaut-servlet, pull requests merged in 2020-09, with the labels that each got.

#58 Dependency upgrades
  gradle.properties
Labels: type: dependency-upgrade

#57 [servlet] Update common files for branch 1.0.x
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#66 [servlet] Update common files for branch 1.0.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#65 [servlet] Update common files for branch master
  .github/workflows/gradle.yml
Labels: relates-to: build

#67 build: bump up micronautTest to 2.1.0
  gradle.properties
  http-server-jetty/build.gradle
Labels: relates-to: build

#68 doc: Release History
  src/main/docs/guide/releaseHistory.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs
