Repository micronaut-projects/micronaut-servlet, pull requests merged in 2021-04, with the labels that each got.

#171 ci: GitHub action files
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build

#176 ci: update github actions files
  .github/workflows/central-sync.yml
  .github/workflows/dependency-update.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
Labels: relates-to: build

#182 ci: set githubCoreBranch 2.5.x
  gradle.properties
Labels: relates-to: build

#189 avoid bean pollution
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyBlockingCrudSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyBlockingPojoCrudSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyCompletableFutureCrudSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyCookieSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyExceptionHandlerSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyHttpPostSpec.groovy
Labels: type: improvement

#184 Don't set response to 404 when returning an http response
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettySslSpec.groovy
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatResponseSpec.groovy
  http-server-tomcat/src/test/resources/logback.xml
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
Labels: type: bug

#192 ci: remove github branch
  gradle.properties
Labels: relates-to: build
