Repository micronaut-projects/micronaut-servlet, pull requests merged in 2022-08, with the labels that each got.

#331 ci: java 11 GraalVM Matrix, Gradle 7.5
  .editorconfig
  .gitattributes
  .github/workflows/central-sync.yml
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#337 ci: project version to 3.3.0-SNAPSHOT
  gradle.properties
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyCorsSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyFileTypeHandlerSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyShutdownSpec.groovy
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatShutdownSpec.groovy
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowShutdownSpec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
Labels: type: dependency-upgrade

#341 fix: A Controller returning a Publisher outputs an empty body
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/RenderJsonTest.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
Labels: type: bug
