Repository micronaut-projects/micronaut-servlet, pull requests merged in 2023-01, with the labels that each got.

#373 Fix Servlet binding for Publisher types
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyHttpPostSpec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpHandler.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/bind/DefaultServletBinderRegistry.java
Labels: type: bug

#371 MN: Update to 3.8.0
  gradle.properties
  gradle/libs.versions.toml
  http-server-jetty/build.gradle
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettySslSpec.groovy
  http-server-jetty/src/test/resources/KeyStore.pkcs12
  http-server-jetty/src/test/resources/TrustStore.jks
  http-server-tomcat/build.gradle
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatSslSpec.groovy
  http-server-tomcat/src/test/resources/KeyStore.pkcs12
  http-server-tomcat/src/test/resources/TrustStore.jks
  http-server-undertow/build.gradle
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowSslSpec.groovy
  http-server-undertow/src/test/resources/KeyStore.pkcs12
  http-server-undertow/src/test/resources/TrustStore.jks
Labels: type: improvement

#383 Bind to localhost instead of 0.0.0.0
  servlet-engine/src/main/java/io/micronaut/servlet/engine/server/ServletServerFactory.java
  src/main/docs/guide/breaks.adoc
  src/main/docs/guide/toc.yml
Labels: relates-to: security, type: breaking

#379 Merge 3.4.x into master
  .github/workflows/graalvm.yml
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.servlet.http-server-tck-module.gradle
  gradle.properties
  gradle/libs.versions.toml
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/ServerContextPathProviderSpec.groovy
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/ServerContextPathProviderSpec.groovy
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/EventsListener.java
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/ServerContextPathProviderSpec.groovy
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowStartStopSpec.groovy
  settings.gradle
  test-suite-http-server-tck-jetty/build.gradle.kts
  test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettytHttpServerTestSuite.java
  test-suite-http-server-tck-jetty/src/test/resources/META-INF/services/io.micronaut.http.server.tck.ServerUnderTestProvider
  test-suite-http-server-tck-jetty/src/test/resources/logback.xml
  test-suite-http-server-tck-tomcat/build.gradle.kts
  test-suite-http-server-tck-tomcat/src/test/java/io/micronaut/http/server/tck/tomcat/tests/TomcatHttpServerTestSuite.java
  test-suite-http-server-tck-tomcat/src/test/resources/META-INF/services/io.micronaut.http.server.tck.ServerUnderTestProvider
  test-suite-http-server-tck-tomcat/src/test/resources/logback.xml
  test-suite-http-server-tck-undertow/build.gradle.kts
  test-suite-http-server-tck-undertow/src/test/java/io/micronaut/http/server/tck/undertow/tests/UndertowHttpServerTestSuite.java
  test-suite-http-server-tck-undertow/src/test/resources/META-INF/services/io.micronaut.http.server.tck.ServerUnderTestProvider
  test-suite-http-server-tck-undertow/src/test/resources/logback.xml
  test-suite-kotlin-jetty/build.gradle
Labels: relates-to: build

#382 Content Type from Error handler should be respected
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyErrorSpec.groovy
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatErrorSpec.groovy
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowErrorSpec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
Labels: type: bug

#368 ci: workflow sync
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#388 remove exclusions
  test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettytHttpServerTestSuite.java
  test-suite-http-server-tck-tomcat/src/test/java/io/micronaut/http/server/tck/tomcat/tests/TomcatHttpServerTestSuite.java
  test-suite-http-server-tck-undertow/src/test/java/io/micronaut/http/server/tck/undertow/tests/UndertowHttpServerTestSuite.java
Labels: type: improvement

#386 refactor: extract resolveContentType method
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
Labels: type: improvement
