Repository micronaut-projects/micronaut-servlet, pull requests merged in 2023-08, with the labels that each got.

#539 docs: remove unnecessary versions
  src/main/docs/guide/jetty.adoc
  src/main/docs/guide/tomcat.adoc
  src/main/docs/guide/undertow.adoc
  src/main/docs/guide/warDeployment.adoc
Labels: type: docs

#544 Document how to use external configuration in WAR deployments
  src/main/docs/guide/toc.yml
  src/main/docs/guide/warDeployment/externalConfig.adoc
Labels: type: docs

#548 Fix Error handler rebinding the body
  gradle/libs.versions.toml
  src/main/docs/guide/knownIssues.adoc
  src/main/docs/guide/toc.yml
  test-suite-http-server-tck-jetty/src/test/java/io/micronaut/http/server/tck/jetty/tests/JettyHttpServerTestSuite.java
  test-suite-http-server-tck-tomcat/src/test/java/io/micronaut/http/server/tck/tomcat/tests/TomcatHttpServerTestSuite.java
  test-suite-http-server-tck-undertow/src/test/java/io/micronaut/http/server/tck/undertow/tests/UndertowHttpServerTestSuite.java
Labels: type: bug

#550 Stop double encoding body when we have a response encoder
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyResponseEncoderSpec.groovy
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatResponseEncoderSpec.groovy
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowFactory.java
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowResponseEncoderSpec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
Labels: type: bug

#555 Fix Jetty with multiple static resources
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyStaticResourceResolutionSpec.groovy
  http-server-jetty/src/test/resources/logback.xml
  http-server-jetty/src/test/resources/nest-test/nested/index.html
  http-server-jetty/src/test/resources/nest-test/something.txt
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatStaticResourceResolutionSpec.groovy
  http-server-tomcat/src/test/resources/nest-test/nested/index.html
  http-server-tomcat/src/test/resources/nest-test/something.txt
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowStaticResourceResolutionSpec.groovy
  http-server-undertow/src/test/resources/nest-test/nested/index.html
  http-server-undertow/src/test/resources/nest-test/something.txt
  servlet-engine/src/main/java/io/micronaut/servlet/engine/server/ServletStaticResourceConfiguration.java
Labels: type: bug

#559 Add Servlet Context if deployed as named WAR file
  .settings.gradle.swp
  servlet-engine/src/main/java/io/micronaut/servlet/engine/initializer/MicronautServletInitializer.java
  src/main/docs/guide/toc.yml
  src/main/docs/guide/warDeployment/warContext.adoc
Labels: type: improvement
