Repository micronaut-projects/micronaut-servlet, pull requests merged in 2024-08, with the labels that each got.

#766 [servlet] Update common files for branch 4.9.x
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#771 [servlet] Update common files for branch 4.9.x
  .github/workflows/release.yml
Labels: relates-to: build

#769 remove unused svm dependency
  buildSrc/src/main/groovy/io.micronaut.build.internal.servlet.implementation.gradle
  gradle/libs.versions.toml
  http-server-tomcat/tomcat.8080/logs/access_log.2024-08-14
Labels: relates-to: graal

#770 Move to core InputStreamByteBody
  gradle/libs.versions.toml
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyNotFoundSpec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ByteArrayBufferFactory.java
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/AvailableByteArrayBody.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/InputStreamByteBody.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java
Labels: type: improvement
