Repository micronaut-projects/micronaut-servlet, pull requests merged in 2024-05, with the labels that each got.

#701 Support Virtual Threads in Jetty & Tomcat
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyVirtualThreadSpec.groovy
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatVirtualThreadEnabler.java
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatVirtualThreadSpec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletConfiguration.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/MicronautServletConfiguration.java
Labels: type: enhancement

#639 Add web-fragment.xml
  servlet-engine/src/main/resources/META-INF/web-fragment.xml
Labels: status: in progress

#702 Make servlet more flexible / support servlet annotations
  http-server-jetty/build.gradle
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyServer.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyServletAnnotationSpec.groovy
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/MyExtraFilter.java
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/MyExtraServlet.java
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/MyFilterFactory.java
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/MyLastFilter.java
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/MyListener.java
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowFactory.java
  servlet-engine/build.gradle
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultMicronautServlet.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/MicronautServletConfiguration.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/annotation/ServletBean.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/annotation/ServletFilterBean.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/initializer/MicronautServletInitializer.java
  servlet-processor/build.gradle.kts
  servlet-processor/src/main/java/io/micronaut/servlet/annotation/processor/ServletAnnotationVisitor.java
  servlet-processor/src/main/java/io/micronaut/servlet/annotation/processor/WebFilterMapper.java
  servlet-processor/src/main/java/io/micronaut/servlet/annotation/processor/WebListenerMapper.java
  servlet-processor/src/main/java/io/micronaut/servlet/annotation/processor/WebServletMapper.java
  servlet-processor/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
  servlet-processor/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
  servlet-processor/src/main/resources/logback.xml
  servlet-processor/src/test/groovy/io/micronaut/servlet/annotation/processor/ServletAnnotationSpec.groovy
  settings.gradle
  src/main/docs/guide/servletAnnotation.adoc
  src/main/docs/guide/toc.yml
Labels: type: enhancement

#706 support for http/2 over plaintext for Jetty & Tomcat
  gradle/libs.versions.toml
  http-server-jetty/build.gradle
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyHttp2OverPlaintextSpec.groovy
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyHttp2Spec.groovy
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TonmcatHttp2OverPlaintextSpec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java
Labels: type: enhancement

#707 Support MessageBodyReader/Writer abstraction in Servlet
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyHttp2Spec.groovy
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletBodyBinder.java
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpResponse.java
Labels: type: enhancement

#708 Attribute binders for ServletConfig/ServletContext
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyParameterBinding2Spec.groovy
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/MyFilterFactory.java
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/ParametersController.java
  servlet-api/build.gradle.kts
  servlet-api/src/main/java/io/micronaut/servlet/api/ServletAttributes.java
  servlet-api/src/main/java/io/micronaut/servlet/api/annotation/ServletBean.java
  servlet-api/src/main/java/io/micronaut/servlet/api/annotation/ServletFilterBean.java
  servlet-engine/build.gradle
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultMicronautServlet.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpResponse.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/bind/DefaultServletBinderRegistry.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/bind/ServletConfigBinder.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/bind/ServletContextBinder.java
  settings.gradle
  src/main/docs/guide/servletAnnotation.adoc
Labels: type: enhancement

#710 [servlet] Update common files for branch 4.8.x
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#711 allow registering other servlet container initializers
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowFactory.java
Labels: type: enhancement

#712 support management port in servlet
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyServer.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyManagementPortSpec.groovy
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatServer.java
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatManagementPortSpec.groovy
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowFactory.java
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowServer.java
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowManagementPortSpec.groovy
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java
  src/main/docs/guide/knownIssues.adoc
Labels: type: enhancement

#713 Support for access log for each servlet server implementation
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyConfiguration.java
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyAccessLogSpec.groovy
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatConfiguration.java
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-tomcat/src/test/groovy/io/micronaut/servlet/tomcat/TomcatAccessLogSpec.groovy
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowConfiguration.java
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowFactory.java
  http-server-undertow/src/test/groovy/io/micronaut/servlet/undertow/UndertowAccessLogSpec.groovy
Labels: type: enhancement

#715 Document access log support and annotation support better
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyServletAnnotationSpec.groovy
  http-server-jetty/src/test/java/io/micronaut/servlet/jetty/MyFilterFactory.java
  http-server-jetty/src/test/resources/application-test.yaml
  src/main/docs/guide/jetty.adoc
  src/main/docs/guide/servletAnnotation.adoc
  src/main/docs/guide/tomcat.adoc
  src/main/docs/guide/undertow.adoc
Labels: type: improvement

#721 [servlet] Update common files for branch 4.9.x
  .github/workflows/gradle.yml
Labels: relates-to: build

#720 Proper streaming ByteBody implementation
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletBodyBinder.java
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/AbstractServletByteBody.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/AvailableByteArrayBody.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/ByteQueue.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/ExtendedInputStream.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/InputStreamByteBody.java
  servlet-core/src/main/java/io/micronaut/servlet/http/body/StreamPair.java
  servlet-core/src/test/groovy/io/micronaut/servlet/http/body/StreamPairSpec.groovy
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpHandler.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/DefaultServletHttpRequest.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/LazyDelegateInputStream.java
Labels: type: improvement

#722 Support configuring minThreads and maxThreads
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyConfigurationSpec.groovy
  http-server-tomcat/src/main/java/io/micronaut/servlet/tomcat/TomcatFactory.java
  http-server-undertow/src/main/java/io/micronaut/servlet/undertow/UndertowFactory.java
  servlet-core/src/main/java/io/micronaut/servlet/http/ServletConfiguration.java
  servlet-engine/src/main/java/io/micronaut/servlet/engine/MicronautServletConfiguration.java
Labels: type: improvement
