Repository micronaut-projects/micronaut-servlet, pull requests merged in 2025-01, with the labels that each got.

#851 Sonatype Scan Gradle Plugin
  .github/workflows/gradle.yml
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.servlet.module.gradle
  gradle/libs.versions.toml
Labels: relates-to: security, relates-to: build

#839 [servlet] Update common files for branch 5.0.x
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  config/checkstyle/suppressions.xml
  gradlew
Labels: relates-to: build

#861 Add support for configuring Jetty connectors and disabling SSL per connector
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyConfiguration.java
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyServer.java
  http-server-jetty/src/test/groovy/io/micronaut/servlet/jetty/JettyManagementPortSpec.groovy
Labels: type: enhancement

#865 improve error for misconfigured static resources in Jetty
  http-server-jetty/src/main/java/io/micronaut/servlet/jetty/JettyFactory.java
Labels: type: bug
